version: '2'

services:
  app:
    image: 'crpsrv:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
         
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db